# Generated by Django 3.0.5 on 2022-05-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=60)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('passward', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=60)),
                ('language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('lamguage', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=4)),
                ('Director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Director')),
            ],
        ),
        migrations.CreateModel(
            name='casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('role', models.CharField(max_length=100)),
                ('acthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('show', models.TimeField()),
                ('costomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Movie')),
            ],
        ),
    ]
