# Generated by Django 4.0.4 on 2022-05-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='costomer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='casting',
            old_name='acthor',
            new_name='actor',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
    ]
